name = "pico_uart_demo"
description = ""
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["pico_uart_demo"]

[test]
runner = "alire"

[[depends-on]]
pico_bsp = "^2.2.0"